version: "3"

services:
  climate-spiral:
    container_name: climate-spiral
    image: ghcr.io/spren9er/climate-spiral
    environment:
      - VIRTUAL_HOST=climate-spiral.spren9er.de
      - LETSENCRYPT_HOST=climate-spiral.spren9er.de

networks:
  default:
    external:
      name: nginx-proxy
